networks:
  vcashier:
    driver: bridge
  postgresql:
    external: true

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_vcashier
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
    volumes:
      - ./backend:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - vcashier

  php:
    image: vixiloc/vcashier-php:latest
    container_name: php_vcashier
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    volumes:
      - ./backend:/var/www/app
    networks:
      - vcashier
      - postgresql