version: '3'

networks:
  laravel:
    driver: bridge

volumes:
  mysql:

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
    volumes:
      - ./backend:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    platform: linux/amd64
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: vcashier
      MYSQL_USER: vcashier
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    container_name: phpmyadmin
    ports:
      - "8002:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    volumes:
      - ./backend:/var/www/app
    ports:
      - "${PHP_HOST_PORT}:${PHP_DOCKER_CONTAINER_PORT}"
    networks:
      - laravel