networks:
  vcashier:
    driver: bridge

volumes:
  pgsql:

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_vcashier
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
    volumes:
      - ./backend:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - vcashier

  db:
    image: postgres
    container_name: pgsql_vcashier
    restart: unless-stopped
    tty: true
    ports:
      - "${PGSQL_HOST_PORT}:${PGSQL_DOCKER_CONTAINER_PORT}"
    volumes:
      - pgsql:/var/lib/pgsql
    environment:
      POSTGRES_DB: vcashier
      POSTGRES_USER: vcashier
      POSTGRES_PASSWORD: ${PGSQL_DB_PASSWORD}
    networks:
      - vcashier

  php:
    image: vixiloc/vcashier-php:1.0.2
    container_name: php_vcashier
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    volumes:
      - ./backend:/var/www/app
    ports:
      - "${PHP_HOST_PORT}:${PHP_DOCKER_CONTAINER_PORT}"
    networks:
      - vcashier